# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('blog', '0002_auto_20150527_1555'),
        ('Bookreview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='myReview',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
    ]
